# Generated by Django 5.2.8 on 2026-07-18 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('punctuality', models.PositiveSmallIntegerField()),
                ('break_compliance', models.PositiveSmallIntegerField()),
                ('customer_comm', models.PositiveSmallIntegerField()),
                ('speed_agility', models.PositiveSmallIntegerField()),
                ('teamwork', models.PositiveSmallIntegerField()),
                ('hygiene_uniform', models.PositiveSmallIntegerField()),
                ('problem_solving', models.PositiveSmallIntegerField()),
                ('feedback_openness', models.PositiveSmallIntegerField()),
                ('energy_motivation', models.PositiveSmallIntegerField()),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluatee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_received', to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('evaluatee', 'date')},
            },
        ),
    ]
