# Generated by Django 5.2.12 on 2026-04-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_staffteam_user_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
        migrations.DeleteModel(
            name='StaffTeam',
        ),
    ]
