# Generated by Django 5.2.8 on 2026-07-24 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_tenant_not_null'),
        ('users', '0007_alter_user_tenant_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='tasks.zone'),
        ),
    ]
