# Generated by Django 5.2.8 on 2026-07-25 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_unit_task_unit'),
        ('users', '0009_remove_user_zone_user_unit_role_user_job_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='tasks.unit'),
        ),
    ]
