# Generated by Django 5.2.8 on 2026-07-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_customer_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='photo_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
