# Generated by Django 5.2.12 on 2026-04-03 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='business_date',
            field=models.DateField(default='2000-01-01', editable=False),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_set', to='assignments.assignment'),
        ),
    ]
