# Generated by Django 5.2.12 on 2026-04-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_tasksubmission_business_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='business_date',
            field=models.DateField(editable=False),
        ),
    ]
