# Generated by Django 5.2.12 on 2026-04-05 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_tasksubmission_business_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='staff_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='photo_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='SubmissionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='assignments.tasksubmission')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
