# Generated by Django 5.2.12 on 2026-04-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_add_submissionphoto_staff_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='coefficient_share',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
