# Generated by Django 5.2.8 on 2026-04-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_add_coefficient_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
