# Generated by Django 5.2.8 on 2026-06-29 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_add_rejection_log'),
        ('tasks', '0006_add_permanent_assignees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assignment',
            name='occurrence',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('user', 'task', 'date', 'occurrence')},
        ),
    ]
