# Generated by Django 5.2.8 on 2026-07-24 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_tenant_not_null'),
        ('trainings', '0004_alter_tenant_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Boş = tüm işletmeye açık. Dolu = sadece o bölgeye özel.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='tasks.zone'),
        ),
        migrations.AlterField(
            model_name='training',
            name='visible_to',
            field=models.JSONField(default=list, help_text='Roller: ["employee"], ["supervisor"], ["employee","supervisor"]'),
        ),
    ]
