# Generated by Django 5.2.12 on 2026-04-02 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskschedule',
            name='month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='month_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='times_per_day',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='frequency',
            field=models.CharField(choices=[('multiple_daily', 'Multiple times per day'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='tasks.task'),
        ),
    ]
