# Generated by Django 5.2.12 on 2026-04-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_workschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('opening', 'Açılış'), ('closing', 'Kapanış'), ('responsibility', 'Sorumluluk Bölgesi'), ('general', 'Genel'), ('special', 'Özel')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='interval_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='frequency',
            field=models.CharField(choices=[('multiple_daily', 'Multiple times per day'), ('interval_daily', 'Every X hours'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20),
        ),
    ]
