# Generated by Django 5.2.12 on 2026-04-06 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_add_category_interval_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='permanent_assignees',
            field=models.ManyToManyField(blank=True, related_name='permanent_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
