# Generated by Django 5.2.8 on 2026-07-24 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_alter_tenant_not_null'),
        ('tasks', '0009_alter_tenant_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Boş = tüm işletmeye açık. Dolu = sadece o bölgeye özel.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='tasks.zone'),
        ),
    ]
