# Generated by Django 5.2.8 on 2026-07-25 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_announcement_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='zone',
        ),
    ]
