# Generated by Django 5.2.8 on 2026-07-25 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_remove_announcement_zone'),
        ('tasks', '0010_unit_task_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Boş = tüm işletmeye açık. Dolu = sadece o birime özel.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='tasks.unit'),
        ),
    ]
